name: lutris
confinement: strict
base: core22
grade: stable
version: 'v0.5.11'

summary: Lutris desktop client in Python / PyGObject
description: |
  Lutris helps you install and play video games from all eras and from most gaming systems. By leveraging and combining existing emulators, engine re-implementations and compatibility layers, it gives you a central interface to launch all your games. The client can connect with existing services like Humble Bundle, GOG and Steam to make your game libraries easily available. Game downloads and installations are automated and can be modified through user made scripts.
  
package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [jammy]
    components: [main, universe]
    architectures: [amd64, i386]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com

  - type: apt
    url: http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [amd64, i386]
    key-id: 5ABCE68FF4633EA42E219156957D2708A03A4626
    key-server: keyserver.ubuntu.com
 #   - type: apt
 #     deb-types: [deb]
 #     components: [main]

# package-repositories:
#   - type: apt
#     deb-types: [deb]
#     components: [main]
#     suites: [$SNAPCRAFT_APT_RELEASE]
#     key-id: 76F1A20FF987672F
#     url: https://dl.winehq.org/wine-builds/ubuntu/

parts:
  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      dpkg --add-architecture i386
      apt update
      
  gnome-extension-hack:
    plugin: dump
    source: .
    override-pull: |
      cat <<'EOF' > gnome-extension-hack
      #!/bin/sh
      rm -f "$XDG_DATA_HOME/icons/hicolor/"* || true
      if [ "$SNAP_ARCH" = "amd64" ]; then
        export LD_LIBRARY_PATH="$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$LD_LIBRARY_PATH"
        export LIBGL_DRIVERS_PATH="$LIBGL_DRIVERS_PATH:$SNAP/usr/lib/i386-linux-gnu/dri"
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIBGL_DRIVERS_PATH"
        export LIBVA_DRIVERS_PATH="$SNAP/usr/lib/i386-linux-gnu/dri"
      fi
      exec "$@"
      EOF
      chmod +x gnome-extension-hack
    organize:
      gnome-extension-hack: bin/gnome-extension-hack

  lutris:
    after: [enable-i386]
    plugin: nil
    source: .
    build-packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - python3
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
      - python3-setuptools
      - python3-distro
      - libpython3-dev
      - python3-pip
      - libcairo2-dev
    override-build: |
      snapcraftctl build
      python3 setup.py build
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - gir1.2-glib-2.0
      - gir1.2-gnomedesktop-3.0
      - gir1.2-gtk-3.0
      - libgnutls30
      - libvulkan1
      - libxrandr2
      - mesa-utils
      - p7zip
      - psmisc
      - python3
      - python3-dbus
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
      - python3-distro
      - unzip
      - wine
      - x11-xserver-utils
      - xterm
      - xz-utils
      - libcairo2-dev
      - libxt-dev
      - libgirepository1.0-dev
      #32 bit 
      - lib32gcc-s1
      - libc6-i386
      - libglu1-mesa:i386
      - libglvnd0:i386
      - libglx-mesa0:i386
      - libgnutls30:i386
      - libvulkan1:i386
      - libx11-6:i386
      #- x11-xserver-utils:i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz

environment:
  HOME: $SNAP_USER_COMMON
  
layout:
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache

apps:
  lutris:
    command: bin/gnome-extension-hack python3 lutris
    plugs:
      - audio-playback
      - browser-support
      - daemon-notify
      - desktop
      - desktop-legacy
      - gsettings
      - hardware-observe
      - home
      - io-ports-control
      - joystick
      - kvm
      - libvirt
      - mount-observe
      - network
      - network-bind
      - network-manager
      - opengl
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7
      - wayland
      - x11

  # wine:
  #   extensions: [gnome-3-28]
  #   command: usr/bin/wine-stable
  
  # wine64:
  #   extensions: [gnome-3-28]
  #   command: usr/bin/wine64-stable
  
  # winecfg:
  #   extensions: [gnome-3-28]
  #   command: usr/bin/winecfg-stable
